apiVersion: organizationwebhook.github.jet.crossplane.io/v1alpha1
kind: Webhook
metadata:
  name: backstage
  namespace: crossplane-system
spec:
  forProvider:
    active: true
    repository: backstage
    events:
    - issues
    configurations:
    - insecureSsl: true
      contentType: "json"
      secretSecretRef:
        name: webhook-secret
        key: secret
      urlSecretRef:
        name: webhook-secret
        key: url